# Generated by Django 4.2 on 2026-01-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sector",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="reviewer_name",
        ),
        migrations.AddField(
            model_name="sector",
            name="name",
            field=models.CharField(default="gildong", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sector",
            name="book",
            field=models.ManyToManyField(related_name="Sector", to="book.book"),
        ),
    ]
