# Generated by Django 6.0.1 on 2026-02-01 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="posted_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="translator",
        ),
        migrations.RemoveField(
            model_name="bookrequest",
            name="translator",
        ),
        migrations.RemoveField(
            model_name="review",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="reviewer_name",
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews_written",
                to="book.user",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sector",
            name="name",
            field=models.CharField(default="General", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_image",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="book",
            name="tags",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="review",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="book.book",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="sector",
            name="book",
            field=models.ManyToManyField(related_name="sectors", to="book.book"),
        ),
    ]
