# Generated by Django 4.2 on 2026-02-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="reviewer_name",
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("fairy_tale", "동화"),
                    ("thriller", "스릴러"),
                    ("mystery", "미스터리/추리"),
                    ("romance", "로맨스"),
                    ("fantasy", "판타지"),
                    ("sf", "SF"),
                    ("essay", "에세이"),
                    ("humanities", "인문"),
                    ("self_dev", "자기계발"),
                    ("business", "경제/경영"),
                    ("it", "IT/개발"),
                    ("history", "역사"),
                    ("science", "과학"),
                    ("etc", "기타"),
                ],
                default="etc",
                max_length=20,
                verbose_name="태그",
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="name",
            field=models.CharField(default="기타", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sector",
            name="book",
            field=models.ManyToManyField(related_name="Sector", to="book.book"),
        ),
    ]
