# Generated by Django 4.2 on 2026-02-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_remove_book_tags_remove_sector_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookrequest",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.user",
            ),
        ),
    ]
