# Generated by Django 4.2 on 2026-01-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookrequest",
            old_name="user",
            new_name="requester",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="writer",
        ),
    ]
