# Generated by Django 4.2 on 2026-02-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_bookrequest_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="difficulty",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="sector",
            name="rule",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sector",
            name="type",
            field=models.CharField(
                choices=[
                    ("PAGE_ASC", "페이지 적은 순"),
                    ("PAGE_DESC", "페이지 많은 순"),
                    ("DIFFICULTY_ASC", "쉬운 책부터"),
                    ("DIFFICULTY_DESC", "어려운 책부터"),
                    ("RATING_DESC", "평점 높은 순"),
                    ("MBTI_MATCH", "MBTI 기반"),
                ],
                default=1,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sector",
            name="book",
            field=models.ManyToManyField(
                blank=True, related_name="Sector", to="book.book"
            ),
        ),
    ]
